# Generated by Django 5.2.1 on 2025-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(default='default_images/default_country_flag.jpg/', upload_to='country_flag_images/'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
