# Generated by Django 5.2.1 on 2025-06-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_alt_text_country_flag_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='rate_from_kes',
            new_name='rate_to_kes',
        ),
    ]
