# Generated by Django 5.2.1 on 2025-06-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_rate_from_kes_exchangerate_rate_to_kes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='rate_to_kes',
            new_name='kes_to_currency',
        ),
    ]
